service:
- docker
env:
  global:
  - TERM=dumb
language: java
jdk: oraclejdk8
addons:
  apt:
    update: true
    packages:
    - libappindicator1
    - fonts-liberation
    - wget
    - bash
    - docker-ce
install: true
before_script:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb >/dev/null
- sudo dpkg -i google-chrome*.deb >/dev/null

script:
- ./gradlew -S clean test headless chrome >/dev/null
- ./gradlew -S clean test chrome
- ./gradlew -S clean check headful phantomjs
- ./gradlew clean
- ./gradlew --stop

- docker build --no-cache --force-rm -t daggerok/e2e-tests
- mkdir -p ~/.gradle/caches/modules-2/files-2.1 ~/.m2/repository
- docker run --rm --name daggerok/run-e2e-tests
  -v ~/.m2/repository:/home/e2e/.m2/repository
  -v ~/.gradle/caches/modules-2/files-2.1:/home/e2e/.gradle/caches/modules-2/files-2.1
  daggerok/e2e-tests
