FROM ubuntu:14.04
LABEL MAINTAINER='Maksim Kostromin https://github.com/daggerok/selenide-in-docker'
ENV DISPLAY=':99' \
    CHROME_DRV_VER='2.39' \
    DEBIAN_FRONTEND='noninteractive' \
    JAVA_HOME='/usr/lib/jvm/java-8-oracle'
#ENV CHROME_BIN='/usr/bin/google-chrome'
ENV PATH="${JAVA_HOME}/bin:${PATH}"
# e2e user with sudo will executex tests
USER root
RUN apt update \
 && apt install -y htop sudo openssh-server vim \
 && useradd -m e2e && echo "e2e:e2e" | chpasswd \
 && adduser e2e sudo \
 && echo "\ne2e ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers \
 && service ssh restart
USER e2e
WORKDIR /home/e2e
# prepare
RUN sudo apt-get update -y \
 && sudo apt-get install -y wget bash software-properties-common
# jdk8
RUN sudo apt-add-repository -y ppa:webupd8team/java \
 && sudo apt-get update -y \
 && sudo echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections \
 && sudo echo debconf shared/accepted-oracle-license-v1-1   seen true | sudo debconf-set-selections \
 && sudo apt-get install -y oracle-java8-installer oracle-java8-set-default oracle-java8-unlimited-jce-policy
# chrome
RUN sudo apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 \
      libatk1.0-0 libcairo2 libcups2 libgdk-pixbuf2.0-0 libgtk-3-0 \
      libnspr4 libnss3 libx11-xcb1 libxss1 xdg-utils \
 && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
 && sudo sudo dpkg -i google-chrome-stable_current_amd64.deb \
 && rm -rf ./google-chrome-stable_current_amd64.deb
# chrome driver
RUN wget https://chromedriver.storage.googleapis.com/${CHROME_DRV_VER}/chromedriver_linux64.zip \
 && unzip chromedriver_linux64.zip \
 && sudo mv -f chromedriver /usr/bin/ \
 && rm -rf chromedriver_linux64.zip
# xvfb stuff
RUN sudo apt-get install -y xvfb xorg xvfb dbus-x11 xfonts-100dpi xfonts-75dpi xfonts-cyrillic \
 && echo '#!/bin/bash \n\
echo "starting Xvfb..." \n\
sudo Xvfb -ac :99 -screen 0 1280x1024x16 & \n' \
      >> ./start-xvfb \
 && chmod +x ./start-xvfb \
 && sudo mv -f ./start-xvfb /usr/bin/start-xvfb

CMD /bin/bash

ARG JAVA_OPTS_ARGS='\
 -Djava.net.preferIPv4Stack=true \
 -XX:+UnlockExperimentalVMOptions \
 -XX:+UseCGroupMemoryLimitForHeap \
 -XshowSettings:vm '
ENV JAVA_OPTS="${JAVA_OPTS} ${JAVA_OPTS_ARGS}"

## chrome based image usage - build base image first:
# docker build -f Dockerfile-e2e-jdk8-chrome-xvfb-base -t daggerok/e2e-jdk8-chrome-xvfb-base .

## create e2e firefox test image based on previous:
# FROM daggerok/e2e-jdk8-chrome-xvfb-base
# WORKDIR /home/e2e/project-directory
# ENTRYPOINT sudo chown -R e2e:e2e . \
#              && . /usr/bin/start-xvfb \
#              && ./gradlew -Si test chrome
# COPY . .
