FROM daggerok/e2e-jdk8-chrome-xvfb-base
LABEL MAINTAINER='Maksim Kostromin https://github.com/daggerok/selenide-in-docker'
WORKDIR /home/e2e/selenide-in-docker
CMD /bin/bash
ENTRYPOINT sudo chown -R e2e:e2e . \
             && . /usr/bin/start-xvfb \
             && ./gradlew -Si check headless chrome
COPY . .

## headless chrome client usage - build image under test:
# docker build -f Dockerfile-e2e-headless-chrome-tests -t daggerok/e2e-headless-chrome-tests .

## run selenide e2e tests in headless chrome client:
# docker run --rm --name run-e2e-headless-chrome-tests daggerok/e2e-headless-chrome-tests
# docker run --rm --name run-e2e-headless-chrome-tests -v ~/.gradle:/home/e2e/.gradle -v ~/.m2:/home/e2e/.m2 daggerok/e2e-headless-chrome-tests

# docker run --rm --name run-e2e-headless-chrome-tests \
#   -v ~/.gradle/caches/modules-2/files-2.1:/home/e2e/.gradle/caches/modules-2/files-2.1 \
#   -v ~/.m2/repository:/home/e2e/.m2/repository \
#   daggerok/e2e-headless-chrome-tests
